version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.3.9-buster

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Install required PHP extensions
          command: sudo docker-php-ext-install bcmath
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run:
          name: Install PHP dependencies
          command: |
            sudo composer self-update
            composer install --no-interaction --prefer-dist --no-suggest
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          name: Run unit tests
          command: ./vendor/bin/phpunit -v
